apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: istio-1.11.4/manifests/charts/base
    repoURL: https://github.com/rinormaloku/istio-helm-installation
    targetRevision: HEAD
    helm:
      releaseName: istio-base
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true

