meshConfig:
  trustDomain: cluster1
  accessLogFile: /dev/stdout
  enableAutoMtls: true
  defaultConfig:
    envoyMetricsService:
      address: enterprise-agent.gloo-mesh:9977
    envoyAccessLogService:
      address: enterprise-agent.gloo-mesh:9977
    proxyMetadata:
      ISTIO_META_DNS_CAPTURE: "true"
      ISTIO_META_DNS_AUTO_ALLOCATE: "true"
      GLOO_MESH_CLUSTER_NAME: cluster1

global:
  meshID: mesh1
  multiCluster:
    clusterName: cluster1
  network: network1
  meshNetworks:
    network1:
      endpoints:
      - fromRegistry: cluster1
      gateways:
      - registryServiceName: istio-ingressgateway.istio-system.svc.cluster.local
        port: 443
    vm-network: {}

pilot:
  env:
    PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
    ENABLE_LEGACY_FSGROUP_INJECTION: "false"
