apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-plane
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: istio-1.11.4/manifests/charts/istio-control/istio-discovery
    repoURL: https://github.com/rinormaloku/istio-helm-installation
    targetRevision: HEAD
    helm: 
      releaseName: control-plane
      valueFiles: 
        - ../../../../../cluster1-values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
